options:
  logging: CLOUD_LOGGING_ONLY  # Or NONE (not recommended)

steps:
- name: 'gcr.io/cloud-builders/docker'
  dir: '.devcontainer'  # Important: specify directory
  args: ['build', '-t', 'gcr.io/$neuralnetlife/streamlit-app', '.']

# Deploy to Cloud Run
- name: 'gcr.io/cloud-builders/gcloud'
  args:
    - 'run'
    - 'deploy'
    - 'streamlit-app'
    - '--image'
    - 'gcr.io/$PROJECT_ID/streamlit-app'
    - '--region'
    - 'us-central1'
    - '--platform'
    - 'managed'
    - '--allow-unauthenticated'
    - '--port'
    - '8501'

images:
  - 'gcr.io/$PROJECT_ID/streamlit-app'